app:
  name: "ecommerce"
  frontend-url: "http://localhost:3000"
  support-email: "support@example.com"

fakestore:
  api:
    base-url: "https://fakestoreapi.com/"

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

spring:
#  mail:
#    host: "smtp.gmail.com"
#    port: 587
#    username: "your-email@gmail.com"
#    password: "your-password"
  # JDBC Connection
  datasource:
    url: "jdbc:postgresql://localhost:5432/ecommerce_db"
    username: "postgres"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"
  # R2DBC Connection (for reactive database access)
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/ecommerce_db"
    username: "postgres"
    password: "admin"

  liquibase:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    user: postgres
    password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
    show-sql: true


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 86400000 # 24 hours
  refresh-token-expiration: 604800000 # 7 days

verification:
  token-expiration: 600000 # 10 minutes
